name: Build and deploy Python app to Azure Web App - cmsprojectudacity

on:
  push:
    branches:
      - master  # or 'main' if that's your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install ODBC dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev libpq-dev gcc g++ python3-dev


      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact for deployment
        run: |
          zip -r app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: cmsprojectudacity  # your Azure Web App name
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: app.zip